import React from "react";
import * as mui from "@mui/material";
import Layout from "../components/layout/Layout";

function AboutPage() {
  return (
    <Layout>
      <mui.Box>
        <mui.Typography
          variant="h1"
          sx={{ fontWeight: "bold", margin: 2, textAlign: "center" }}
        >
          About
        </mui.Typography>
      </mui.Box>

      <mui.Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "left",
          justifyContent: "left",
          textAlign: "left",
          padding: 5,
        }}
      >
        <mui.Typography
          variant="h3"
          sx={{ fontWeight: "bold", marginBottom: 2 }}
        >
          What is SyntheaWeb?
        </mui.Typography>

        <mui.Typography
          variant="body1"
          sx={{ maxWidth: "800px", marginBottom: 4, lineHeight: 1.6 }}
        >
          SyntheaWeb is a platform developed for the Medical University of
          Vienna to simplify access to synthetic medical data generated by
          Synthea™. It supports researchers, students, and healthcare
          professionals by providing realistic, artificial datasets that
          prioritize privacy and comply with strict data protection regulations.
        </mui.Typography>

        <mui.Typography
          variant="h3"
          sx={{ fontWeight: "bold", marginBottom: 2 }}
        >
          What is Synthea?
        </mui.Typography>
        <mui.Typography
          variant="body1"
          sx={{ maxWidth: "800px", marginBottom: 4, lineHeight: 1.6 }}
        >
          Synthea™ is an open-source synthetic patient generator developed by
          The MITRE Corporation. It creates realistic healthcare data for entire
          populations, simulating patient demographics and various aspects of
          medical care. These datasets are entirely fictional, making them ideal
          for research, education, and software testing without compromising
          real patient privacy.
          <br />
          <br />
          For more information, visit{" "}
          <mui.Link
            href="https://synthetichealth.github.io/synthea/"
            target="_blank"
            rel="noopener noreferrer"
            sx={{
              color: "primary.main",
              textDecoration: "none",
              "&:hover": {
                textDecoration: "underline",
              },
            }}
          >
            https://synthetichealth.github.io/synthea/
          </mui.Link>
        </mui.Typography>

        <mui.Box
          sx={{
            display: "flex",
            flexDirection: "column",
            gap: 2,
            maxWidth: "600px",
            marginBottom: 4,
            width: "100%",
          }}
        >
          <mui.Typography variant="h3" sx={{ fontWeight: "bold" }}>
            Our Goals
          </mui.Typography>
          <mui.List sx={{ listStyleType: "disc", pl: 4 }}>
            <mui.ListItem sx={{ display: "list-item", pl: 0 }}>
              <mui.Typography variant="body1">
                User-Friendly Experience: Provide an intuitive platform for
                generating synthetic healthcare data.
              </mui.Typography>
            </mui.ListItem>

            <mui.ListItem sx={{ display: "list-item", pl: 0 }}>
              <mui.Typography variant="body1">
                Support for Research and Education: Promote advancements in
                healthcare and data science by offering an accessible platform.
              </mui.Typography>
            </mui.ListItem>
          </mui.List>
        </mui.Box>

        <mui.Box sx={{}}>
          <mui.Typography variant="h6" sx={{ marginBottom: 1 }}>
            Contact Us
          </mui.Typography>
          <mui.Typography variant="body1">
            For inquiries, please reach out to:{" "}
            <mui.Link
              href="mailto:mhd.jouned@meduniwien.ac.at"
              sx={{
                color: "primary.main",
                textDecoration: "none",
                "&:hover": { textDecoration: "underline" },
              }}
            >
              mhd.jouned@meduniwien.ac.at
            </mui.Link>
          </mui.Typography>
        </mui.Box>
      </mui.Box>
    </Layout>
  );
}

export default AboutPage;
